# Generated by Django 3.0.5 on 2022-12-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarriageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_type_name', models.CharField(choices=[('seated', 'Seated'), ('coupe', 'Coupe'), ('platzkart', 'Platzkart')], max_length=25)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('fail', 'Fail'), ('success', 'Success'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tickets.ArrivalPoint')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('arrival_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ArrivalPoint')),
                ('carriage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.Carriage')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ArrivalPoint')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_tickets', to='tickets.Order')),
            ],
        ),
        migrations.CreateModel(
            name='RouteToArrivalPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.DateTimeField()),
                ('arrival_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ArrivalPoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Route')),
            ],
        ),
    ]
